### ISSUE TITLE
Changed argument for `__init__`

### ISSUE THREAD

**Issue by CRTified** [devture/matrix-synapse-shared-secret-auth#16]
It looks like the argument `api` got renamed to `account_handler`, causing `matrix-synapse` to refuse to start:
```
Feb 18 00:56:19 cloudbox systemd[1]: Starting Synapse Matrix homeserver...
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: This server is configured to use 'matrix.org' as its trusted key server via the
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: 'trusted_key_servers' config option. 'matrix.org' is a good choice for a key
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: server since it is long-lived, stable and trusted. However, some admins may
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: wish to use another server for this purpose.
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: To suppress this warning and continue using 'matrix.org', admins should set
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: 'suppress_key_server_warning' to 'true' in homeserver.yaml.
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: --------------------------------------------------------------------------------
Feb 18 00:56:21 cloudbox synapse[2315949]: root: [main] ***** STARTING SERVER *****
Feb 18 00:56:21 cloudbox synapse[2315949]: root: [main] Server /nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/bin/synapse_homeserver version 1.52.0
Feb 18 00:56:21 cloudbox synapse[2315949]: synapse.handlers.auth: [sentinel] Error while initializing <class 'shared_secret_authenticator.SharedSecretAuthProvider'>: __init__() got an unexpected keyword argument 'account_handler'
Feb 18 00:56:21 cloudbox synapse[2315949]: synapse.app._base: [sentinel] Error during startup
                                           Traceback (most recent call last):
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 227, in wrapper
                                               await cb(*args, **kwargs)
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/homeserver.py", line 405, in start
                                               await _base.start(hs)
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 444, in start
                                               load_legacy_password_auth_providers(hs)
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1909, in load_legacy_password_auth_providers
                                               load_single_legacy_password_auth_provider(
                                             File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1920, in load_single_legacy_password_auth_provider
                                               provider = module(config=config, account_handler=api)
                                           TypeError: __init__() got an unexpected keyword argument 'account_handler'
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: Error during startup:
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: Traceback (most recent call last):
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 227, in wrapper
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     await cb(*args, **kwargs)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/homeserver.py", line 405, in start
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     await _base.start(hs)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/app/_base.py", line 444, in start
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     load_legacy_password_auth_providers(hs)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1909, in load_legacy_password_auth_providers
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     load_single_legacy_password_auth_provider(
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:   File "/nix/store/h2gxxs9f2lfwkwcmmkyi4swzyp18jvca-matrix-synapse-1.52.0/lib/python3.9/site-packages/synapse/handlers/auth.py", line 1920, in load_single_legacy_password_auth_provider
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]:     provider = module(config=config, account_handler=api)
Feb 18 00:56:21 cloudbox synapse_homeserver[2315949]: TypeError: __init__() got an unexpected keyword argument 'account_handler'
Feb 18 00:56:21 cloudbox systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Feb 18 00:56:21 cloudbox systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.
Feb 18 00:56:21 cloudbox systemd[1]: Failed to start Synapse Matrix homeserver.
Feb 18 00:56:21 cloudbox systemd[1]: matrix-synapse.service: Consumed 2.805s CPU time, no IP traffic.
Feb 18 00:56:22 cloudbox systemd[1]: matrix-synapse.service: Scheduled restart job, restart counter is at 3.
Feb 18 00:56:22 cloudbox systemd[1]: Stopped Synapse Matrix homeserver.
Feb 18 00:56:22 cloudbox systemd[1]: matrix-synapse.service: Consumed 2.805s CPU time, no IP traffic.
```

I got it working with renaming the argument appropriately:
```patch
diff --git a/shared_secret_authenticator.py b/shared_secret_authenticator.py
index c24d8dd..55efc0e 100644
--- a/shared_secret_authenticator.py
+++ b/shared_secret_authenticator.py
@@ -30,7 +30,7 @@ from synapse import module_api
 logger = logging.getLogger(__name__)
 
 class SharedSecretAuthProvider:
-    def __init__(self, config: dict, api: module_api):
+    def __init__(self, config: dict, account_handler: module_api):
         for k in ('shared_secret',):
             if k not in config:
                 raise KeyError('Required `{0}` configuration key not found'.format(k))
@@ -38,7 +38,7 @@ class SharedSecretAuthProvider:
         m_login_password_support_enabled = bool(config['m_login_password_support_enabled']) if 'm_login_password_support_enabled' in config else False
         com_devture_shared_secret_auth_support_enabled = bool(config['com_devture_shared_secret_auth_support_enabled']) if 'com_devture_shared_secret_auth_support_enabled' in config else True
 
-        self.api = api
+        self.api = account_handler
         self.shared_secret = config['shared_secret']
 
         auth_checkers: Optional[Dict[Tuple[str, Tuple], CHECK_AUTH_CALLBACK]] = {}
@@ -54,7 +54,7 @@ class SharedSecretAuthProvider:
 
         logger.info('Enabled login types: %s', enabled_login_types)
 
-        api.register_password_auth_provider_callbacks(
+        self.api.register_password_auth_provider_callbacks(
             auth_checkers=auth_checkers,
         )
 ```

Sorry that I didn't bother bisecting the synapse version that introduced the behavior, it just appeared when switching to 1.52.0.

**Comment by CRTified** [comment]
Or is this just an incompatibility of v2?

**Comment by spantaleev** [comment]
Something seems off. I can't reproduce it.

Looking at your backtrace, it seems like you might be registering v2 in `password_providers`.

v1 is meant to be registered there.

v2 is [a new type of Synapse module](https://matrix-org.github.io/synapse/v1.52/modules/index.html), which goes into Synapse's `modules` configuration key. Registering it via `password_providers` may have worked until now, but it seems like it's no more.

Our [changelog entry for v2](https://github.com/devture/matrix-synapse-shared-secret-auth/blob/master/CHANGELOG.md#version-2) explicitly mentions that upgrading to v2 requires switching to `modules`

**Comment by CRTified** [comment]
That is the case. Now that I know what I had to look for, I also found it in the `README.md`. Sorry for the noise, I somehow missed that completely.
