### ISSUE TITLE
The module no longer loads in Synapse v1.23.0

### ISSUE THREAD

**Issue by apetresc** [devture/matrix-synapse-shared-secret-auth#7]
Ever since the latest Synapse release a few hours ago, the module simply fails to load:

```python
synapse_1           | 2020-11-18T18:15:15.523461690Z Traceback (most recent call last):
synapse_1           | 2020-11-18T18:15:15.523503767Z   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
synapse_1           | 2020-11-18T18:15:15.523509063Z     return _run_code(code, main_globals, None,
synapse_1           | 2020-11-18T18:15:15.523512497Z   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
synapse_1           | 2020-11-18T18:15:15.523515924Z     exec(code, run_globals)
synapse_1           | 2020-11-18T18:15:15.523519157Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 512, in <module>
synapse_1           | 2020-11-18T18:15:15.523522937Z     main()
synapse_1           | 2020-11-18T18:15:15.523526080Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 507, in main
synapse_1           | 2020-11-18T18:15:15.523529522Z     hs = setup(sys.argv[1:])
synapse_1           | 2020-11-18T18:15:15.523532589Z   File "/usr/local/lib/python3.8/site-packages/synapse/app/homeserver.py", line 341, in setup
synapse_1           | 2020-11-18T18:15:15.523536136Z     config = HomeServerConfig.load_or_generate_config(
synapse_1           | 2020-11-18T18:15:15.523539350Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 721, in load_or_generate_config
synapse_1           | 2020-11-18T18:15:15.523542743Z     obj.parse_config_dict(
synapse_1           | 2020-11-18T18:15:15.523545784Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 740, in parse_config_dict
synapse_1           | 2020-11-18T18:15:15.523549061Z     self.invoke_all(
synapse_1           | 2020-11-18T18:15:15.523552117Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/_base.py", line 369, in invoke_all
synapse_1           | 2020-11-18T18:15:15.523555491Z     res[name] = getattr(config, func_name)(*args, **kwargs)
synapse_1           | 2020-11-18T18:15:15.523558683Z   File "/usr/local/lib/python3.8/site-packages/synapse/config/password_auth_providers.py", line 47, in read_config
synapse_1           | 2020-11-18T18:15:15.523562078Z     (provider_class, provider_config) = load_module(
synapse_1           | 2020-11-18T18:15:15.523565299Z   File "/usr/local/lib/python3.8/site-packages/synapse/util/module_loader.py", line 33, in load_module
synapse_1           | 2020-11-18T18:15:15.523568720Z     module = importlib.import_module(module)
synapse_1           | 2020-11-18T18:15:15.523571943Z   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
synapse_1           | 2020-11-18T18:15:15.523575200Z     return _bootstrap._gcd_import(name[level:], package, level)
synapse_1           | 2020-11-18T18:15:15.523578511Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
synapse_1           | 2020-11-18T18:15:15.523581881Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
synapse_1           | 2020-11-18T18:15:15.523585156Z   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
synapse_1           | 2020-11-18T18:15:15.523588456Z ModuleNotFoundError: No module named 'shared_secret_authenticator'
```

There's nothing in the logs that shows what sort of load error it's encountering, just that it can't load it. Reverting back to Synapse v1.22.1 solves the problem, so presumably there's some breaking change in the Synapse API?

**Comment by spantaleev** [comment]
I'm not sure how you're installing it, but maybe you've put it on the wrong path. It needs to be copied/mounted under `/usr/local/lib/python3.8/site-packages` in your case.

**Comment by apetresc** [comment]
Oh, whoops! Yeah, that was the change - the `v1.22.1` tag uses python3.7 while `v1.23.0` upgraded to python3.8!

Thank you, and sorry for the spurious issue!
